<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-01T19:49:40 CDT" name="Default suite" finished-at="2024-06-01T19:49:52 CDT" duration-ms="11828">
    <groups>
    </groups>
    <test started-at="2024-06-01T19:49:40 CDT" name="Default test" finished-at="2024-06-01T19:49:52 CDT" duration-ms="11828">
      <class name="tests.Contacts">
        <test-method is-config="true" signature="doConfigReport()[pri:0, instance:tests.Contacts@ec0c838]" started-at="2024-06-01T19:49:40 CDT" name="doConfigReport" finished-at="2024-06-01T19:49:40 CDT" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doConfigReport -->
        <test-method is-config="true" signature="preConditions(java.lang.reflect.Method)[pri:0, instance:tests.Contacts@ec0c838]" started-at="2024-06-01T19:49:40 CDT" name="preConditions" finished-at="2024-06-01T19:49:42 CDT" duration-ms="2202" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.Contacts.verifyErrorMessageWhileCreatingNewViewInContacts_TC30() throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preConditions -->
        <test-method signature="verifyErrorMessageWhileCreatingNewViewInContacts_TC30()[pri:0, instance:tests.Contacts@ec0c838]" started-at="2024-06-01T19:49:42 CDT" name="verifyErrorMessageWhileCreatingNewViewInContacts_TC30" finished-at="2024-06-01T19:49:51 CDT" duration-ms="9261" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at pages.ContactsPage.verifyUniqueViewNameEntered(ContactsPage.java:212)
at tests.Contacts.verifyErrorMessageWhileCreatingNewViewInContacts_TC30(Contacts.java:187)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyErrorMessageWhileCreatingNewViewInContacts_TC30 -->
        <test-method is-config="true" signature="postConditions(java.lang.reflect.Method)[pri:0, instance:tests.Contacts@ec0c838]" started-at="2024-06-01T19:49:51 CDT" name="postConditions" finished-at="2024-06-01T19:49:52 CDT" duration-ms="195" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.Contacts.verifyErrorMessageWhileCreatingNewViewInContacts_TC30() throws java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postConditions -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:tests.Contacts@ec0c838]" started-at="2024-06-01T19:49:52 CDT" name="cleanup" finished-at="2024-06-01T19:49:52 CDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="tearDownConfigReport()[pri:0, instance:tests.Contacts@ec0c838]" started-at="2024-06-01T19:49:52 CDT" name="tearDownConfigReport" finished-at="2024-06-01T19:49:52 CDT" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownConfigReport -->
      </class> <!-- tests.Contacts -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
